name: publish
on:
  release:
    types:
      - published
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: true
      - run: devbox run -- pnpm install --frozen-lockfile
      - run: devbox run -- pnpm publish --access=public
  publish-docker:
    uses: y13i/actions/.github/workflows/docker.yml@main
    secrets:
      dockerhub-access-token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
